### ISSUE TITLE
White Screen Hangs

### ISSUE THREAD

**Issue by icefire82G** [Plailect/b9sTool#2]
Hey Plailect, first of all, thanks for being super diligent with the guide. You are practically a saint at this point.

So I've gotten to the part where I need to backup f0f1, and, with boot.nds on the root of my SD card an a working save injected into four swords, I still get a hang on the white screen upon booting it.

It's currently on an N3DSXL with 11.4OWF, after transferring from my O3DSXL with 11.4Luma/Sighax

Hopefully it's some bug or something, and I'm not totally screwed here. Thanks in advance for any help, yo.

EDIT: The bottom screen flashes a light green for a split second early on, but after that it just hands completely. Any idea what I should do?

**Comment by srwgin** [comment]
the same problem
can boot dgTool boot.nds
but can not boot b9sTool boot.nds

**Comment by nateisaspy** [comment]
Same here can boot dgTool boot.nds
but can not boot b9sTool boot.nds
Using O3dsXL system transferred from a o3ds armloader + Luma

**Comment by Plailect** [comment]
Is everyone encountering this issue using 4swordshax?

**Comment by MelonGx** [comment]
@Plailect Yes. Everyone B9STool hangs but dgTool OK are using 4swordhax.

**Comment by Plailect** [comment]
Fixed! The binary has been replaced with one compiled with old libnds. Binaries compiled with new libnds will fail to boot when launched by 4swordshax (just shows a white screen).

**Comment by MelonGx** [comment]
Many thanks :)

**Comment by zoogie** [comment]
@Plailect - could you tell me the libnds revision that got b9stool working with 4swordshax? thx!
